# -*- coding: utf-8 -*-
"""
/***************************************************************************
 katalog_fitur
                                 A QGIS plugin
 Plugin untuk memudahkan pengkatalogan fitur spasial
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-31
        copyright            : (C) 2023 by Teknik Geodesi UGM
        email                : farda.fadila@mail.ugm.ac.id
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load katalog_fitur class from file katalog_fitur.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .katalog_fitur import katalog_fitur
    return katalog_fitur(iface)
